version: "3.8"

services:
    backend: 
        container_name: backend
        build: ./material-applications/example-backend
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        depends_on:
            - redis
            - postgres
        ports: 
            - 8080:8080
    frontend:
        container_name: frontend
        image: frontend
        build: ./material-applications/example-frontend
        depends_on:
            - backend
        ports:
            - 5000:5000
    redis:
        container_name: redis
        image: redis
        restart: unless-stopped
        command: redis-server
        ports: 
            - 6379:6379
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        volumes:
            - ./database:/var/lib/postgresql/data

volumes:
  database:
  cache: