version: '3.8'

services:
  frontend:
    build: material-applications/example-frontend
    image: frontend
    container_name: frontend-container
    ports:
      - 5000:5000

  backend: 
    build: material-applications/example-backend
    image: backend
    container_name: backend-container
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  
  redis:
    image: redis
    container_name: redis-container
    restart: unless-stopped
    command: redis-server