version: "3.8"

services:
    backend: 
        container_name: backend
        build: ./material-applications/example-backend
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        ports: 
            - 8080:8080
    frontend:
        container_name: frontend
        image: frontend
        build: ./material-applications/example-frontend
        ports:
            - 5000:5000
    redis:
        container_name: redis
        image: redis
        command: redis-server
        ports: 
            - 6379:6379
    postgres:
        container_name: postgres
        image: postgres:13.6-alpine 
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        volumes:
            - ./database:/var/lib/postgresql/data
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.config:/etc/nginx/nginx.conf
    

volumes:
  database:
  cache: